#!/usr/bin/env php
<?php
if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "\nThe payload utility not installed. Use \"composer install\" or \"composer update\" for install.\n\n";
    exit(1);
}

error_reporting(E_ERROR);

include __DIR__ . '/vendor/autoload.php';

use App\Console\ArgumentHolder;
use App\ContentLoader;
use App\PayloadHandler;
use Domain\Site;

const
DEFAULT_TIMEOUT = 60, DEFAULT_LEVEL = PHP_INT_MAX, SITE_INDEX = 0;

$consoleArguments = new ArgumentHolder();

$url = $consoleArguments->getParameter(SITE_INDEX);

$paramsError = (filter_var($url, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED | FILTER_FLAG_HOST_REQUIRED) ===
                false) || (($parsed = parse_url($url)) === false);
$paramsError |= (!in_array($parsed['scheme'] ?? [], ['http', 'https'], true));
if ($paramsError) {
    echo "\nIncorrect URL ", $url, "\n\nUse the utility as follows.\n\n";
}

if ($paramsError || $url === null || $consoleArguments->getOption('h') !== null) {
    echo <<<HELPTEXT
Load tester to evaluate the performance and load stability of the API.
php payload [-h] [-t<maximum execution time>] [-d<directory>] [-m<HTTP method>] [-i<iterations>] [-c<number of competing requests>] [-H<HTTP header>] [-D<HTTP body>] <url>

<url> - site URL
-h - help (this text)
-t - maximum script execution time, seconds (default 60)
-d - directory for saving the report (default - current)
-m - HTTP method for requests (GET, POST, PUT, DELETE, default GET)
-H - HTTP header for requests. There may be several headers, see example.
-i - number of iterations to average response time (default 100)
-c - number of competing requests in each iteration (default 1)
-D - string placed in the body of each POST or PUT request
-F - full report with data for each iteration

Example:
php payload -t180 -d~/reports -H"Content-Type application/x-www-form-urlencoded" -H"Accept-Encoding gzip, deflate" -mPOST -i100 -c1 https://api.site.com/GraphQL -D'query=query(\$criterion: ServiceListInterface) {
    allService(criterion: \$criterion) {
        item,
        texts {
            locale,
            text
        }
    }
}&variables={
  "criterion": {}
}'

HELPTEXT;
    exit(1);
}

$method                   = ($consoleArguments->getOption('m') ?? 'GET');
$iterations               = (int) ($consoleArguments->getOption('i') ?? 100);
$concurrentRequestsNumber = (int) ($consoleArguments->getOption('c') ?? 1);
$headers                  = (array) ($consoleArguments->getOption('H') ?? []);
$data                     = $consoleArguments->getOption('D');
$timeout                  = (int) ($consoleArguments->getOption('t') ?? DEFAULT_TIMEOUT);

set_time_limit($timeout);
$start = microtime(true);

$loader = ContentLoader::getInstance();
$loader->setHeaders($headers);
$loader->setMethod($method);
$loader->setData($data);
$handler = new PayloadHandler(new Site($url), $loader, $concurrentRequestsNumber, $iterations);

$report = $handler->handle($url);
if ($consoleArguments->getOption('F') === '') {
    $report->withDetails();
}
echo $report->getContent();

$fullFilename = ($consoleArguments->getOption('d') ?? '.') . '/' . $report->getDefaultFilename();

if (file_put_contents($fullFilename, $report->getContent()) === false) {
    echo "\n\nFile ", $fullFilename, " cann't be saved.";
    exit(1);
}

echo "\nFile ", $fullFilename, " saved.\n", sprintf("Full runtime = %.4f sec.\n", microtime(true) - $start);